[directories]
training = "data/train"
datasets = "data/sets"

[files]
training = 'data/train/data.txt'
data     = 'data/train/data_pi.obj'

[data]
production = 'data/train/data.txt'

[preperation]
sets = ["chatterbot", "custom"]

[tokenizer]
production = 'tokenizer/p_tokenizer_pi.obj'
oov_token  = 1
max_word_count = 30
num_words = 6000

[model]
production = 'models/production.h5'

[training]
batch_size = 100
epochs = 1000
